server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://rm-wz9l1pya91wv7bdfm.mysql.rds.aliyuncs.com:3306/ads?useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: ads_server
    password: 2Ad9c4A70
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
      web-stat-filter:
        enabled: true
        profile-enable: true
      stat-view-servlet:
        enabled: true
#        allow: 183.48.20.5/24,58.248.229.148/24,59.41.207.22/24
        login-username: druid
        login-password: cAe3d8dF13
  task:
    scheduling:
      pool:
        size: 8
    execution:
      pool:
        core-size: 32

click_record_create_days: 8

system:
  web:
    scheme: https
    domain: 2020funfantasy.cn