server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads?useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
