server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads?useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
      web-stat-filter:
        enabled: true
        profile-enable: true
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: cAe3d8dF13
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
