server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://rm-wz9l1pya91wv7bdfm.mysql.rds.aliyuncs.com:3306/ads?useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: ads_server
    password: Aa6631990
  task:
    scheduling:
      pool:
        size: 8
    execution:
      pool:
        core-size: 32

click_record_create_days: 8

system:
  web:
    domain: 2020funfantasy.cn